/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insurance;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Mastaer Save
 */
public class delete extends javax.swing.JFrame {

    /**
     * Creates new form delete
     */
    boolean m1,m2,m3,m4;
    public delete() {
        initComponents();
           m1=m2=m3=m4=false;
        redp.setVisible(false);
        setLocation(300, 10);
        t1e1.setVisible(false);
         t1e2.setVisible(false);
          t2e1.setVisible(false);
           t3e1.setVisible(false);
            t2e2.setVisible(false);
             t3e2.setVisible(false);
          this.jPanel2.setBackground(new Color(0,0,0,100));
        this.s2.setBackground(new Color(255,255,255,100));
        this.s1.setBackground(new Color(255,255,255,100));
        this.s3.setBackground(new Color(255,255,255,100));
        this.l1.setBackground(new Color(0,0,0,100));
        this.l2.setBackground(new Color(0,0,0,100));
        this.l3.setBackground(new Color(0,0,0,100));
        this.l4.setBackground(new Color(0,0,0,100));
        this.l5.setBackground(new Color(0,0,0,100));
        this.b1.setBackground(new Color(0,0,0,100));
        this.b2.setBackground(new Color(0,0,0,100));
        this.b3.setBackground(new Color(0,0,0,100));
        this.b4.setBackground(new Color(0,0,0,100));
        this.pp.setBackground(new Color(255,255,255,100));
         this.t1.setCaretColor(Color.WHITE);
        this.t2.setCaretColor(Color.WHITE);
        this.t3.setCaretColor(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1e2 = new javax.swing.JLabel();
        t1e1 = new javax.swing.JLabel();
        t3e2 = new javax.swing.JLabel();
        t3e1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        blue = new javax.swing.JPanel();
        pi = new javax.swing.JLabel();
        redp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        l1 = new javax.swing.JPanel();
        l2 = new javax.swing.JPanel();
        l3 = new javax.swing.JPanel();
        s1 = new javax.swing.JPanel();
        t2e2 = new javax.swing.JLabel();
        t2e1 = new javax.swing.JLabel();
        s2 = new javax.swing.JPanel();
        l4 = new javax.swing.JPanel();
        l5 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        s3 = new javax.swing.JPanel();
        pp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        b1 = new javax.swing.JPanel();
        b2 = new javax.swing.JPanel();
        b3 = new javax.swing.JPanel();
        b4 = new javax.swing.JPanel();
        pp1 = new javax.swing.JPanel();
        pp2 = new javax.swing.JPanel();
        pp3 = new javax.swing.JPanel();
        pp4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1e2.setForeground(new java.awt.Color(204, 255, 255));
        t1e2.setText("Ssn is 9 numbers");
        getContentPane().add(t1e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 110, 20));

        t1e1.setForeground(new java.awt.Color(204, 255, 255));
        t1e1.setText("   Ssn is requred");
        getContentPane().add(t1e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 110, -1));

        t3e2.setForeground(new java.awt.Color(204, 255, 255));
        t3e2.setText("Last name just alphabets");
        getContentPane().add(t3e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 150, -1));

        t3e1.setForeground(new java.awt.Color(204, 255, 255));
        t3e1.setText("Last name is requred");
        getContentPane().add(t3e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 590, 130, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Deletion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 410, -1));

        blue.setLayout(null);

        pi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insurance/2.png"))); // NOI18N
        pi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                piMouseEntered(evt);
            }
        });
        blue.add(pi);
        pi.setBounds(0, 0, 60, 55);

        getContentPane().add(blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 60, 50));

        redp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redpMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                redpMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insurance/3.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout redpLayout = new javax.swing.GroupLayout(redp);
        redp.setLayout(redpLayout);
        redpLayout.setHorizontalGroup(
            redpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redpLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        redpLayout.setVerticalGroup(
            redpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redpLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(redp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 60, 50));

        javax.swing.GroupLayout l1Layout = new javax.swing.GroupLayout(l1);
        l1.setLayout(l1Layout);
        l1Layout.setHorizontalGroup(
            l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        l1Layout.setVerticalGroup(
            l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        javax.swing.GroupLayout l2Layout = new javax.swing.GroupLayout(l2);
        l2.setLayout(l2Layout);
        l2Layout.setHorizontalGroup(
            l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        l2Layout.setVerticalGroup(
            l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, 380));

        javax.swing.GroupLayout l3Layout = new javax.swing.GroupLayout(l3);
        l3.setLayout(l3Layout);
        l3Layout.setHorizontalGroup(
            l3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        l3Layout.setVerticalGroup(
            l3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, -1, 380));

        s1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout s1Layout = new javax.swing.GroupLayout(s1);
        s1.setLayout(s1Layout);
        s1Layout.setHorizontalGroup(
            s1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        s1Layout.setVerticalGroup(
            s1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        t2e2.setForeground(new java.awt.Color(204, 255, 255));
        t2e2.setText("First name just alphabets");
        getContentPane().add(t2e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 160, 10));

        t2e1.setBackground(new java.awt.Color(204, 255, 255));
        t2e1.setForeground(new java.awt.Color(204, 255, 255));
        t2e1.setText("First name is requred");
        getContentPane().add(t2e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, 150, -1));

        s2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout s2Layout = new javax.swing.GroupLayout(s2);
        s2.setLayout(s2Layout);
        s2Layout.setHorizontalGroup(
            s2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        s2Layout.setVerticalGroup(
            s2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, -1, -1));

        javax.swing.GroupLayout l4Layout = new javax.swing.GroupLayout(l4);
        l4.setLayout(l4Layout);
        l4Layout.setHorizontalGroup(
            l4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        l4Layout.setVerticalGroup(
            l4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 390, -1));

        javax.swing.GroupLayout l5Layout = new javax.swing.GroupLayout(l5);
        l5.setLayout(l5Layout);
        l5Layout.setHorizontalGroup(
            l5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        l5Layout.setVerticalGroup(
            l5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 390, -1));

        t1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(204, 204, 204));
        t1.setText("Ssn");
        t1.setBorder(null);
        t1.setOpaque(false);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t1MouseExited(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 312, 70));

        t2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(204, 204, 204));
        t2.setText("First name");
        t2.setBorder(null);
        t2.setOpaque(false);
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t2MouseExited(evt);
            }
        });
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 312, 70));

        t3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t3.setForeground(new java.awt.Color(204, 204, 204));
        t3.setText("Last name");
        t3.setBorder(null);
        t3.setOpaque(false);
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t3MouseExited(evt);
            }
        });
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 312, 70));

        s3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout s3Layout = new javax.swing.GroupLayout(s3);
        s3.setLayout(s3Layout);
        s3Layout.setHorizontalGroup(
            s3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        s3Layout.setVerticalGroup(
            s3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, -1));

        pp.setBackground(new java.awt.Color(204, 204, 204));
        pp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ppMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Delete");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel9KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout ppLayout = new javax.swing.GroupLayout(pp);
        pp.setLayout(ppLayout);
        ppLayout.setHorizontalGroup(
            ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(23, 23, 23))
        );
        ppLayout.setVerticalGroup(
            ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, 100, -1));

        javax.swing.GroupLayout b1Layout = new javax.swing.GroupLayout(b1);
        b1.setLayout(b1Layout);
        b1Layout.setHorizontalGroup(
            b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        b1Layout.setVerticalGroup(
            b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 630, 130, 100));

        javax.swing.GroupLayout b2Layout = new javax.swing.GroupLayout(b2);
        b2.setLayout(b2Layout);
        b2Layout.setHorizontalGroup(
            b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        b2Layout.setVerticalGroup(
            b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 630, 140, 100));

        javax.swing.GroupLayout b3Layout = new javax.swing.GroupLayout(b3);
        b3.setLayout(b3Layout);
        b3Layout.setHorizontalGroup(
            b3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        b3Layout.setVerticalGroup(
            b3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 730, 390, 40));

        javax.swing.GroupLayout b4Layout = new javax.swing.GroupLayout(b4);
        b4.setLayout(b4Layout);
        b4Layout.setHorizontalGroup(
            b4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        b4Layout.setVerticalGroup(
            b4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, 120, -1));

        pp1.setBackground(new java.awt.Color(4, 73, 150));

        javax.swing.GroupLayout pp1Layout = new javax.swing.GroupLayout(pp1);
        pp1.setLayout(pp1Layout);
        pp1Layout.setHorizontalGroup(
            pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pp1Layout.setVerticalGroup(
            pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(pp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 730, -1, 0));

        pp2.setBackground(new java.awt.Color(4, 73, 150));

        javax.swing.GroupLayout pp2Layout = new javax.swing.GroupLayout(pp2);
        pp2.setLayout(pp2Layout);
        pp2Layout.setHorizontalGroup(
            pp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pp2Layout.setVerticalGroup(
            pp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(pp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, -1, -1));

        pp3.setBackground(new java.awt.Color(4, 73, 150));

        javax.swing.GroupLayout pp3Layout = new javax.swing.GroupLayout(pp3);
        pp3.setLayout(pp3Layout);
        pp3Layout.setHorizontalGroup(
            pp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pp3Layout.setVerticalGroup(
            pp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(pp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, -1, 60));

        pp4.setBackground(new java.awt.Color(4, 73, 150));

        javax.swing.GroupLayout pp4Layout = new javax.swing.GroupLayout(pp4);
        pp4.setLayout(pp4Layout);
        pp4Layout.setHorizontalGroup(
            pp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pp4Layout.setVerticalGroup(
            pp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(pp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 660, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insurance/all.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1296, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redpMouseClicked
        // TODO add your handling code hereset
        setVisible(false);
    }//GEN-LAST:event_redpMouseClicked

    private void redpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redpMouseExited
        redp.setVisible(false);
        blue.setVisible(true);
    }//GEN-LAST:event_redpMouseExited

    private void piMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piMouseEntered
        blue.setVisible(false);
        redp.setVisible(true);
    }//GEN-LAST:event_piMouseEntered

    private void t1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseExited
        if(this.t1.getText().equals("")&&m1)
        {this.t1.setText("Ssn");this.t1e1.setVisible(false);this.t1e2.setVisible(false);}
        else if(this.t1.getText().equals("Ssn")&&m1)this.t1e2.setVisible(false);
        else{
            if(m1){
                int number=0;int length=0;
                for(int i=0;i<this.t1.getText().length();i++){length++;
                    if(Character.isDigit(this.t1.getText().charAt(i)))number++;}
                if(number==this.t1.getText().length()&&length==9){this.t1e2.setVisible(false);}else this.t1e2.setVisible(true);
    }//GEN-LAST:event_t1MouseExited
        }}
    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed

    }//GEN-LAST:event_t1ActionPerformed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        if(evt.getKeyCode()!=KeyEvent.VK_ENTER&&evt.getKeyCode()!=KeyEvent.VK_UP&&
            evt.getKeyCode()!=KeyEvent.VK_DOWN){

            m1=true;

            this.t1e1.setVisible(false);
            int number=0;int length=0;

            if(this.t1.getText().equals("Ssn"))
            this.t1.setText("");

            for(int i=0;i<this.t1.getText().length();i++){length++;
                if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
            if(number==this.t1.getText().length()&&length==8){
                this.t1e2.setVisible(false);}

        }
        else if(evt.getKeyCode()==KeyEvent.VK_UP)  {
            this.t3.requestFocus(rootPaneCheckingEnabled);
            if(this.t1.getText().equals("")&&m1){
                this.t1.setText("Ssn");this.t1e1.setVisible(false);this.t1e2.setVisible(false);}
            else if(this.t1.getText().equals("Ssn")&&m1)
            {this.t1e2.setVisible(false);this.t1e1.setVisible(false);}
            else{
                if(m1){
                    int number=0;int length=0;

                    for(int i=0;i<this.t1.getText().length();i++){length++;
                        if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
                    if(number==this.t1.getText().length()&&length==9){

                        this.t1e2.setVisible(false);}else{
                        this.t1e2.setVisible(true);}

                }}}
                else if(evt.getKeyCode()==KeyEvent.VK_DOWN)  {
                    this.t2.requestFocus(rootPaneCheckingEnabled);
                    if(this.t1.getText().equals("")&&m1){
                        this.t1.setText("Ssn");this.t1e1.setVisible(false);this.t1e2.setVisible(false);}
                    else if(this.t1.getText().equals("Ssn")&&m1)
                    {this.t1e2.setVisible(false);this.t1e1.setVisible(false);}
                    else{
                        if(m1){
                            int number=0;int length=0;

                            for(int i=0;i<this.t1.getText().length();i++){length++;
                                if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
                            if(number==this.t1.getText().length()&&length==9){

                                this.t1e2.setVisible(false);this.t1e1.setVisible(false); }else{
                                this.t1e2.setVisible(true);}

                        }} }
                        else{
                            this.t2.requestFocus(rootPaneCheckingEnabled);
                            if(this.t1.getText().equals("")&&m1){
                                this.t1.setText("Ssn");this.t1e1.setVisible(false);this.t1e2.setVisible(false);}
                            else if(this.t1.getText().equals("Ssn")&&m1)
                            {this.t1e2.setVisible(false);this.t1e1.setVisible(false);}
                            else{
                                if(m1){
                                    int number=0;int length=0;

                                    for(int i=0;i<this.t1.getText().length();i++){length++;
                                        if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
                                    if(number==this.t1.getText().length()&&length==9){
                                        this.t1e2.setVisible(false);}
                                    else{t1e2.setVisible(true);}

                                    if(this.t1.getText().equals("")){this.t1.setText("Ssn");this.t1e2.setVisible(false);this.t1e1.setVisible(false);}
                                }}
                            }
    }//GEN-LAST:event_t1KeyPressed

    private void t2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseExited
        if(this.t2.getText().equals("")&&m2)
                {this.t2.setText("First name");this.t2e1.setVisible(false);this.t2e2.setVisible(false);}
                else if(this.t2.getText().equals("First name")&&m1)this.t2e2.setVisible(false);
             else{
                    if(m2){
                 int number=0;
                 for(int i=0;i<this.t2.getText().length();i++)
                     if(Character.isAlphabetic(this.t2.getText().charAt(i)))number++;
                 if(number==this.t2.getText().length()){this.t2e2.setVisible(false);}else this.t2e2.setVisible(true);
                    }}
    }//GEN-LAST:event_t2MouseExited

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
        if(evt.getKeyCode()!=KeyEvent.VK_ENTER&&evt.getKeyCode()!=KeyEvent.VK_UP&&
                   evt.getKeyCode()!=KeyEvent.VK_DOWN){
         m2=true;t2e1.setVisible(false);
         if(this.t2.getText().equals("First name")) 
        this.t2.setText("");
       }
      else if(evt.getKeyCode()==KeyEvent.VK_DOWN)  {if(this.t2.getText().equals("")&&m2){this.t2.setText("First name");
           this.t2e2.setVisible(false);  this.t2e1.setVisible(false);}
      else if(this.t2.getText().equals("First name")&&m2){this.t2e1.setVisible(false);this.t2e2.setVisible(false);}else{
          if(m2){
          int number=0;
          for(int i=0;i<this.t2.getText().length();i++){
                if (Character.isAlphabetic(this.t2.getText().charAt(i)))number++;}

            if(number==this.t2.getText().length()){
                this.t2e2.setVisible(false);this.t2e1.setVisible(false);}
            else{this.t2e2.setVisible(true);this.t2e1.setVisible(false);}}}
            this.t3.requestFocus(rootPaneCheckingEnabled);}
          else if(evt.getKeyCode()==KeyEvent.VK_UP)  {if(this.t2.getText().equals("")&&m2){this.t2.setText("First name");
           this.t2e2.setVisible(false);  this.t2e1.setVisible(false); } else if(this.t2.getText().equals("First name")&&m2)
           {this.t2e1.setVisible(false);this.t2e2.setVisible(false);}
           else{ if(m2){
              int number=0;
              for(int i=0;i<this.t2.getText().length();i++){
                if (Character.isAlphabetic(this.t1.getText().charAt(i)))number++;}

            if(number==this.t2.getText().length()){
                this.t2e2.setVisible(false);this.t2e1.setVisible(false);}
            else{this.t2e2.setVisible(true);this.t2e1.setVisible(false);}}}
          this.t1.requestFocus(rootPaneCheckingEnabled);}
      else{
        this.t3.requestFocus(rootPaneCheckingEnabled);
        if(this.t2.getText().equals("")&&m2)this.t2.setText("First name");
        else if(this.t2.getText().equals("First name")&&m2)
        {this.t2e1.setVisible(false);this.t2e2.setVisible(false);}
        else{
            if(m2){
            int number=0;
            for(int i=0;i<this.t2.getText().length();i++){
                if (Character.isAlphabetic(this.t2.getText().charAt(i)))number++;}

            if(number==this.t2.getText().length()){
                this.t2e2.setVisible(false);this.t2e1.setVisible(false);}
            else{this.t2e2.setVisible(true);this.t2e1.setVisible(false);}}}
       
          }
    }//GEN-LAST:event_t2KeyPressed

    private void t3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MouseExited
        if(this.t3.getText().equals("")&&m3)
                {this.t3.setText("Last name");this.t3e1.setVisible(false);this.t3e2.setVisible(false);}
                else if(this.t3.getText().equals("Last name")&&m3)this.t3e2.setVisible(false);
             else{
                    if(m3){
                 int number=0;
                 for(int i=0;i<this.t3.getText().length();i++)
                     if(Character.isAlphabetic(this.t3.getText().charAt(i)))number++;
                 if(number==this.t3.getText().length()){this.t3e2.setVisible(false);}else this.t3e2.setVisible(true);
                    
                    }}    
    }//GEN-LAST:event_t3MouseExited

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
       if(evt.getKeyCode()!=KeyEvent.VK_ENTER&&evt.getKeyCode()!=KeyEvent.VK_UP&&
                   evt.getKeyCode()!=KeyEvent.VK_DOWN){
                     m3=true;this.t3e1.setVisible(false);
          if(this.t3.getText().equals("Last name")) 
        this.t3.setText("");
       }
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN)  {if(this.t3.getText().equals("")&&m3){this.t3.setText("Last name");
           this.t3e2.setVisible(false);  this.t3e1.setVisible(false);}else if(this.t3.getText().equals("Last name")&&m3)
           {this.t3e1.setVisible(false);this.t3e2.setVisible(false);}
           else{
               if(m3){
          int number=0;
          for(int i=0;i<this.t3.getText().length();i++){
                if (Character.isAlphabetic(this.t3.getText().charAt(i)))number++;}

            if(number==this.t3.getText().length()){
                this.t3e2.setVisible(false);this.t3e1.setVisible(false);}
            else{this.t3e2.setVisible(true);this.t3e1.setVisible(false);}}}
            this.t1.requestFocus(rootPaneCheckingEnabled);}
          else if(evt.getKeyCode()==KeyEvent.VK_UP)  {if(this.t3.getText().equals("")&&m3)
          {this.t3.setText("Last name");
           this.t3e2.setVisible(false);  this.t3e1.setVisible(false); }
          else if(this.t3.getText().equals("Last name")&&m3)
          {this.t3e1.setVisible(false);this.t3e2.setVisible(false);}
          else{ 
              if(m3){
              int number=0;
              for(int i=0;i<this.t3.getText().length();i++){
                if (Character.isAlphabetic(this.t3.getText().charAt(i)))number++;}

            if(number==this.t3.getText().length()){
                this.t3e2.setVisible(false);this.t3e1.setVisible(false);}
            else{this.t3e2.setVisible(true);this.t3e1.setVisible(false);}}} 
          this.t2.requestFocus(rootPaneCheckingEnabled);}
      else{
              this.t1.requestFocus(rootPaneCheckingEnabled);
         m1=m2=m3=m4=false;

        boolean b1,b3,b4;
        if(this.t3.getText().equals("")){this.t2e1.setVisible(true);b1=false;this.t2e2.setVisible(false);}
        else if(this.t2.getText().equals("First name"))
        {this.t2e1.setVisible(true);this .t2e2.setVisible(false);this.t2.setText("");b1=false;}
        else {
            int number=0;
            for(int i=0;i<this.t2.getText().length();i++){
                if (Character.isAlphabetic(this.t2.getText().charAt(i)))number++;}

            if(number==this.t2.getText().length()){
                this.t2e2.setVisible(false);b1=true;this.t2e1.setVisible(false);}
            else{this.t2e2.setVisible(true);b1=false;this.t2e1.setVisible(false);}}

      
        if(this.t3.getText().equals(""))
        {this.t3e1.setVisible(true);b3=false;this.t3e2.setVisible(false);}
        else if(this.t3.getText().equals("Last name"))
        {this.t3e1.setVisible(true);this.t3.setText("");b3=false;this.t3e2.setVisible(false);}
        else {
            int number=0;
            for(int i=0;i<this.t3.getText().length();i++){
                if (Character.isAlphabetic(this.t3.getText().charAt(i)))number++;}
            if(number==this.t3.getText().length()){
                this.t3e1.setVisible(false);b3=true;t3e2.setVisible(false);}
            else{this.t3e2.setVisible(true);b3=false;this.t3e1.setVisible(false);}}

        if(this.t1.getText().equals("")){this.t1e1.setVisible(true);b4=false;this.t1e2.setVisible(false);}
        else if(this.t1.getText().equals("Ssn"))
        {this.t1e1.setVisible(true);this.t1.setText("");b4=false;t1e2.setVisible(false);}
        else {
            int number=0;int length=0;
            for(int i=0;i<this.t1.getText().length();i++){length++;
                if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
            if(number==this.t1.getText().length()&&length==9){
                this.t1e1.setVisible(false);b4=true;this.t1e2.setVisible(false);}
            else {b4=false; this.t1e2.setVisible(true);this.t1e1.setVisible(false);}}

       
        /////////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////////////////////////
        if(b1&&b3&&b4){
            this.t1.setText("Ssn");
             this.t2.setText("First name");
              this.t3.setText("Last name");
              this.t1.requestFocus(rootPaneCheckingEnabled);
            
           m1=m2=m3=m4=false;
        redp.setVisible(false);
     
        t1e1.setVisible(false);
         t1e2.setVisible(false);
          t2e1.setVisible(false);
           t3e1.setVisible(false);
            t2e2.setVisible(false);
             t3e2.setVisible(false);
              JOptionPane.showMessageDialog(null,"Sucssed");
              
            //Raed//
        }
    }
    }//GEN-LAST:event_t3KeyPressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        m1=m2=m3=m4=false;

        boolean b1,b3,b4;
        if(this.t3.getText().equals("")){this.t2e1.setVisible(true);b1=false;this.t2e2.setVisible(false);}
        else if(this.t2.getText().equals("First name"))
        {this.t2e1.setVisible(true);this .t2e2.setVisible(false);this.t2.setText("");b1=false;}
        else {
            int number=0;
            for(int i=0;i<this.t2.getText().length();i++){
                if (Character.isAlphabetic(this.t2.getText().charAt(i)))number++;}

            if(number==this.t2.getText().length()){
                this.t2e2.setVisible(false);b1=true;this.t2e1.setVisible(false);}
            else{this.t2e2.setVisible(true);b1=false;this.t2e1.setVisible(false);}}

      
        if(this.t3.getText().equals(""))
        {this.t3e1.setVisible(true);b3=false;this.t3e2.setVisible(false);}
        else if(this.t3.getText().equals("Last name"))
        {this.t3e1.setVisible(true);this.t3.setText("");b3=false;this.t3e2.setVisible(false);}
        else {
            int number=0;
            for(int i=0;i<this.t3.getText().length();i++){
                if (Character.isAlphabetic(this.t3.getText().charAt(i)))number++;}
            if(number==this.t3.getText().length()){
                this.t3e1.setVisible(false);b3=true;t3e2.setVisible(false);}
            else{this.t3e2.setVisible(true);b3=false;this.t3e1.setVisible(false);}}

        if(this.t1.getText().equals("")){this.t1e1.setVisible(true);b4=false;this.t1e2.setVisible(false);}
        else if(this.t1.getText().equals("Ssn"))
        {this.t1e1.setVisible(true);this.t1.setText("");b4=false;t1e2.setVisible(false);}
        else {
            int number=0;int length=0;
            for(int i=0;i<this.t1.getText().length();i++){length++;
                if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
            if(number==this.t1.getText().length()&&length==9){
                this.t1e1.setVisible(false);b4=true;this.t1e2.setVisible(false);}
            else {b4=false; this.t1e2.setVisible(true);this.t1e1.setVisible(false);}}

       
          /////////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////////////////////////
        if(b1&&b3&&b4){
            this.t1.setText("Ssn");
             this.t2.setText("First name");
              this.t3.setText("Last name");
              this.t1.requestFocus(rootPaneCheckingEnabled);
            
           m1=m2=m3=m4=false;
        redp.setVisible(false);
     
        t1e1.setVisible(false);
         t1e2.setVisible(false);
          t2e1.setVisible(false);
           t3e1.setVisible(false);
            t2e2.setVisible(false);
             t3e2.setVisible(false);
              JOptionPane.showMessageDialog(null,"Sucssed");
              
            //Raed//
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
 this.pp1.setOpaque(false);
        this.pp1.repaint();
        this.pp2.setOpaque(false);
        this.pp2.repaint();
        this.pp3.setOpaque(false);
        this.pp3.repaint();
        this.pp4.setOpaque(false);
        this.pp4.repaint();
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel9KeyPressed

    }//GEN-LAST:event_jLabel9KeyPressed

    private void ppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppMouseClicked
       m1=m2=m3=m4=false;

        boolean b1,b3,b4;
        if(this.t3.getText().equals("")){this.t2e1.setVisible(true);b1=false;this.t2e2.setVisible(false);}
        else if(this.t2.getText().equals("First name"))
        {this.t2e1.setVisible(true);this .t2e2.setVisible(false);this.t2.setText("");b1=false;}
        else {
            int number=0;
            for(int i=0;i<this.t2.getText().length();i++){
                if (Character.isAlphabetic(this.t2.getText().charAt(i)))number++;}

            if(number==this.t2.getText().length()){
                this.t2e2.setVisible(false);b1=true;this.t2e1.setVisible(false);}
            else{this.t2e2.setVisible(true);b1=false;this.t2e1.setVisible(false);}}

      
        if(this.t3.getText().equals(""))
        {this.t3e1.setVisible(true);b3=false;this.t3e2.setVisible(false);}
        else if(this.t3.getText().equals("Last name"))
        {this.t3e1.setVisible(true);this.t3.setText("");b3=false;this.t3e2.setVisible(false);}
        else {
            int number=0;
            for(int i=0;i<this.t3.getText().length();i++){
                if (Character.isAlphabetic(this.t3.getText().charAt(i)))number++;}
            if(number==this.t3.getText().length()){
                this.t3e1.setVisible(false);b3=true;t3e2.setVisible(false);}
            else{this.t3e2.setVisible(true);b3=false;this.t3e1.setVisible(false);}}

        if(this.t1.getText().equals("")){this.t1e1.setVisible(true);b4=false;this.t1e2.setVisible(false);}
        else if(this.t1.getText().equals("Ssn"))
        {this.t1e1.setVisible(true);this.t1.setText("");b4=false;t1e2.setVisible(false);}
        else {
            int number=0;int length=0;
            for(int i=0;i<this.t1.getText().length();i++){length++;
                if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
            if(number==this.t1.getText().length()&&length==9){
                this.t1e1.setVisible(false);b4=true;this.t1e2.setVisible(false);}
            else {b4=false; this.t1e2.setVisible(true);this.t1e1.setVisible(false);}}

         /////////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////////////////////////
        if(b1&&b3&&b4){
            this.t1.setText("Ssn");
             this.t2.setText("First name");
              this.t3.setText("Last name");
              this.t1.requestFocus(rootPaneCheckingEnabled);
            
           m1=m2=m3=m4=false;
        redp.setVisible(false);
     
        t1e1.setVisible(false);
         t1e2.setVisible(false);
          t2e1.setVisible(false);
           t3e1.setVisible(false);
            t2e2.setVisible(false);
             t3e2.setVisible(false);
              JOptionPane.showMessageDialog(null,"Sucssed");
              
            //Raed//
        }
    }//GEN-LAST:event_ppMouseClicked

    private void ppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppMouseEntered
        this.pp1.setOpaque(false);
        this.pp1.repaint();
        this.pp2.setOpaque(false);
        this.pp2.repaint();
        this.pp3.setOpaque(false);
        this.pp3.repaint();
        this.pp4.setOpaque(false);
        this.pp4.repaint();
    }//GEN-LAST:event_ppMouseEntered

    private void ppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppMouseExited
        this.pp1.setOpaque(true);
        this.pp1.repaint();
        this.pp2.setOpaque(true);
        this.pp2.repaint();
        this.pp3.setOpaque(true);
        this.pp3.repaint();
        this.pp4.setOpaque(true);
        this.pp4.repaint();
    }//GEN-LAST:event_ppMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel b1;
    private javax.swing.JPanel b2;
    private javax.swing.JPanel b3;
    private javax.swing.JPanel b4;
    private javax.swing.JPanel blue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel l1;
    private javax.swing.JPanel l2;
    private javax.swing.JPanel l3;
    private javax.swing.JPanel l4;
    private javax.swing.JPanel l5;
    private javax.swing.JLabel pi;
    private javax.swing.JPanel pp;
    private javax.swing.JPanel pp1;
    private javax.swing.JPanel pp2;
    private javax.swing.JPanel pp3;
    private javax.swing.JPanel pp4;
    private javax.swing.JPanel redp;
    private javax.swing.JPanel s1;
    private javax.swing.JPanel s2;
    private javax.swing.JPanel s3;
    private javax.swing.JTextField t1;
    private javax.swing.JLabel t1e1;
    private javax.swing.JLabel t1e2;
    private javax.swing.JTextField t2;
    private javax.swing.JLabel t2e1;
    private javax.swing.JLabel t2e2;
    private javax.swing.JTextField t3;
    private javax.swing.JLabel t3e1;
    private javax.swing.JLabel t3e2;
    // End of variables declaration//GEN-END:variables
}
