/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insurance;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sun.net.www.content.image.png;

/**
 *
 * @author Ammar
 */
public class acount extends javax.swing.JFrame {

    /**
     * Creates new form acount
     */
    boolean click=true,isprivate,ispublic,red;
    boolean m1,m2,m3,m4,m5,m6,m7;
    public acount() {
        initComponents();
        m1=m2=m3=m4=m5=m6=m7=isprivate=ispublic=false;

          this.background.setSize(this.getWidth(), this.getHeight());
       
         this.title.setBackground(new Color(0,0,0,100));
         this.l1.setBackground(new Color(0,0,0,100));
         this.l2.setBackground(new Color(0,0,0,100));
         this.l3.setBackground(new Color(0,0,0,100));
         this.l4.setBackground(new Color(0,0,0,100));
         this.l5.setBackground(new Color(0,0,0,100));
         this.l6.setBackground(new Color(0,0,0,100));
         this.l7.setBackground(new Color(0,0,0,100));
         this.l8.setBackground(new Color(0,0,0,100));
         this.l9.setBackground(new Color(0,0,0,100));
         this.l10.setBackground(new Color(0,0,0,100));
         this.l11.setBackground(new Color(0,0,0,100));
         this.l12.setBackground(new Color(0,0,0,100));
         this.l13.setBackground(new Color(0,0,0,100));
         this.s1.setBackground(new Color(255,255,255,100));
         this.s2.setBackground(new Color(255,255,255,100));
         this.s3.setBackground(new Color(255,255,255,100));
         this.s4.setBackground(new Color(255,255,255,100));
         this.s5.setBackground(new Color(255,255,255,100));
         this.s6.setBackground(new Color(255,255,255,100));
         this.s7.setBackground(new Color(255,255,255,100));
         this.t1e2.setVisible(false);
         this.t2e2.setVisible(false);
         this.t3e1.setVisible(false);
         this.t4e.setVisible(false);
         this.t5e.setVisible(false);
         this.t6e.setVisible(false);
         this.t1e1.setVisible(false);
         this.t2e1.setVisible(false);
           this.t3e2.setVisible(false);
           pi.setVisible(true);
          this.pp.setBackground(new Color(255,255,255,100));
          this.t1.setCaretColor(Color.WHITE);
          this.t2.setCaretColor(Color.WHITE);
          this.t3.setCaretColor(Color.WHITE);
          this.t4.setCaretColor(Color.WHITE);
          this.t5.setCaretColor(Color.WHITE);
          this.t6.setCaretColor(Color.WHITE);
            setLocation(300, 10);
            redp.setVisible(false);
          
         
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t3e2 = new javax.swing.JLabel();
        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JPanel();
        l2 = new javax.swing.JPanel();
        l3 = new javax.swing.JPanel();
        s1 = new javax.swing.JPanel();
        l4 = new javax.swing.JPanel();
        s2 = new javax.swing.JPanel();
        l5 = new javax.swing.JPanel();
        s5 = new javax.swing.JPanel();
        s6 = new javax.swing.JPanel();
        s4 = new javax.swing.JPanel();
        s3 = new javax.swing.JPanel();
        l6 = new javax.swing.JPanel();
        l7 = new javax.swing.JPanel();
        pivee = new javax.swing.JPanel();
        priv = new javax.swing.JLabel();
        priveline = new javax.swing.JPanel();
        privelight = new javax.swing.JPanel();
        l8 = new javax.swing.JPanel();
        publ = new javax.swing.JPanel();
        pupll = new javax.swing.JLabel();
        pupline = new javax.swing.JPanel();
        puplight = new javax.swing.JPanel();
        l9 = new javax.swing.JPanel();
        t4e = new javax.swing.JLabel();
        t2e2 = new javax.swing.JLabel();
        t3e1 = new javax.swing.JLabel();
        t1e2 = new javax.swing.JLabel();
        t5e = new javax.swing.JLabel();
        t6e = new javax.swing.JLabel();
        t1e1 = new javax.swing.JLabel();
        t2e1 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        s7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        l12 = new javax.swing.JPanel();
        l10 = new javax.swing.JPanel();
        pp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        blue = new javax.swing.JPanel();
        pi = new javax.swing.JLabel();
        l11 = new javax.swing.JPanel();
        l13 = new javax.swing.JPanel();
        pp4 = new javax.swing.JPanel();
        pp2 = new javax.swing.JPanel();
        pp1 = new javax.swing.JPanel();
        pp3 = new javax.swing.JPanel();
        redp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 1000));
        getContentPane().setLayout(null);

        t3e2.setForeground(new java.awt.Color(204, 255, 255));
        t3e2.setText("Color just alphabets");
        getContentPane().add(t3e2);
        t3e2.setBounds(700, 430, 150, 15);

        title.setToolTipText("Member Login");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Add Account");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(title);
        title.setBounds(450, 130, 400, 82);

        javax.swing.GroupLayout l1Layout = new javax.swing.GroupLayout(l1);
        l1.setLayout(l1Layout);
        l1Layout.setHorizontalGroup(
            l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        l1Layout.setVerticalGroup(
            l1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l1);
        l1.setBounds(460, 230, 380, 10);

        javax.swing.GroupLayout l2Layout = new javax.swing.GroupLayout(l2);
        l2.setLayout(l2Layout);
        l2Layout.setHorizontalGroup(
            l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        l2Layout.setVerticalGroup(
            l2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(l2);
        l2.setBounds(450, 230, 10, 560);

        javax.swing.GroupLayout l3Layout = new javax.swing.GroupLayout(l3);
        l3.setLayout(l3Layout);
        l3Layout.setHorizontalGroup(
            l3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        l3Layout.setVerticalGroup(
            l3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(l3);
        l3.setBounds(840, 230, 10, 560);

        s1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout s1Layout = new javax.swing.GroupLayout(s1);
        s1.setLayout(s1Layout);
        s1Layout.setHorizontalGroup(
            s1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        s1Layout.setVerticalGroup(
            s1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(s1);
        s1.setBounds(460, 240, 70, 70);

        javax.swing.GroupLayout l4Layout = new javax.swing.GroupLayout(l4);
        l4.setLayout(l4Layout);
        l4Layout.setHorizontalGroup(
            l4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        l4Layout.setVerticalGroup(
            l4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l4);
        l4.setBounds(460, 310, 380, 10);

        s2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout s2Layout = new javax.swing.GroupLayout(s2);
        s2.setLayout(s2Layout);
        s2Layout.setHorizontalGroup(
            s2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        s2Layout.setVerticalGroup(
            s2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(s2);
        s2.setBounds(460, 320, 70, 70);

        javax.swing.GroupLayout l5Layout = new javax.swing.GroupLayout(l5);
        l5.setLayout(l5Layout);
        l5Layout.setHorizontalGroup(
            l5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        l5Layout.setVerticalGroup(
            l5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l5);
        l5.setBounds(460, 390, 380, 10);

        s5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout s5Layout = new javax.swing.GroupLayout(s5);
        s5.setLayout(s5Layout);
        s5Layout.setHorizontalGroup(
            s5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        s5Layout.setVerticalGroup(
            s5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(s5);
        s5.setBounds(460, 560, 70, 70);

        s6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout s6Layout = new javax.swing.GroupLayout(s6);
        s6.setLayout(s6Layout);
        s6Layout.setHorizontalGroup(
            s6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        s6Layout.setVerticalGroup(
            s6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(s6);
        s6.setBounds(460, 640, 70, 70);

        s4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout s4Layout = new javax.swing.GroupLayout(s4);
        s4.setLayout(s4Layout);
        s4Layout.setHorizontalGroup(
            s4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        s4Layout.setVerticalGroup(
            s4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(s4);
        s4.setBounds(460, 480, 70, 70);

        s3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout s3Layout = new javax.swing.GroupLayout(s3);
        s3.setLayout(s3Layout);
        s3Layout.setHorizontalGroup(
            s3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        s3Layout.setVerticalGroup(
            s3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(s3);
        s3.setBounds(460, 400, 70, 70);

        javax.swing.GroupLayout l6Layout = new javax.swing.GroupLayout(l6);
        l6.setLayout(l6Layout);
        l6Layout.setHorizontalGroup(
            l6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        l6Layout.setVerticalGroup(
            l6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l6);
        l6.setBounds(460, 470, 380, 10);

        javax.swing.GroupLayout l7Layout = new javax.swing.GroupLayout(l7);
        l7.setLayout(l7Layout);
        l7Layout.setHorizontalGroup(
            l7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        l7Layout.setVerticalGroup(
            l7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l7);
        l7.setBounds(460, 550, 380, 10);

        pivee.setBackground(new java.awt.Color(7, 89, 165));
        pivee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piveeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                piveeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                piveeMouseExited(evt);
            }
        });

        priv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priv.setForeground(new java.awt.Color(204, 204, 204));
        priv.setText("Private");
        priv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                privMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                privMouseEntered(evt);
            }
        });

        priveline.setBackground(new java.awt.Color(7, 89, 165));

        javax.swing.GroupLayout privelineLayout = new javax.swing.GroupLayout(priveline);
        priveline.setLayout(privelineLayout);
        privelineLayout.setHorizontalGroup(
            privelineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        privelineLayout.setVerticalGroup(
            privelineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        privelight.setBackground(new java.awt.Color(7, 89, 165));

        javax.swing.GroupLayout privelightLayout = new javax.swing.GroupLayout(privelight);
        privelight.setLayout(privelightLayout);
        privelightLayout.setHorizontalGroup(
            privelightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        privelightLayout.setVerticalGroup(
            privelightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout piveeLayout = new javax.swing.GroupLayout(pivee);
        pivee.setLayout(piveeLayout);
        piveeLayout.setHorizontalGroup(
            piveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piveeLayout.createSequentialGroup()
                .addGroup(piveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piveeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(privelight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priv, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piveeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(priveline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        piveeLayout.setVerticalGroup(
            piveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piveeLayout.createSequentialGroup()
                .addGroup(piveeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piveeLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(priv))
                    .addGroup(piveeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(privelight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priveline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        getContentPane().add(pivee);
        pivee.setBounds(610, 730, 100, 40);

        javax.swing.GroupLayout l8Layout = new javax.swing.GroupLayout(l8);
        l8.setLayout(l8Layout);
        l8Layout.setHorizontalGroup(
            l8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        l8Layout.setVerticalGroup(
            l8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l8);
        l8.setBounds(460, 630, 380, 10);

        publ.setBackground(new java.awt.Color(5, 92, 169));
        publ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                publMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                publMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                publMouseExited(evt);
            }
        });

        pupll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pupll.setForeground(new java.awt.Color(204, 204, 204));
        pupll.setText("Public");
        pupll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pupllMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pupllMouseEntered(evt);
            }
        });

        pupline.setBackground(new java.awt.Color(5, 92, 169));

        javax.swing.GroupLayout puplineLayout = new javax.swing.GroupLayout(pupline);
        pupline.setLayout(puplineLayout);
        puplineLayout.setHorizontalGroup(
            puplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        puplineLayout.setVerticalGroup(
            puplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        puplight.setBackground(new java.awt.Color(5, 92, 169));

        javax.swing.GroupLayout puplightLayout = new javax.swing.GroupLayout(puplight);
        puplight.setLayout(puplightLayout);
        puplightLayout.setHorizontalGroup(
            puplightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        puplightLayout.setVerticalGroup(
            puplightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout publLayout = new javax.swing.GroupLayout(publ);
        publ.setLayout(publLayout);
        publLayout.setHorizontalGroup(
            publLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publLayout.createSequentialGroup()
                .addGroup(publLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(publLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(puplight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pupll, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pupline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        publLayout.setVerticalGroup(
            publLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publLayout.createSequentialGroup()
                .addGroup(publLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(publLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(pupll))
                    .addGroup(publLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(puplight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pupline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        getContentPane().add(publ);
        publ.setBounds(750, 730, 90, 40);

        javax.swing.GroupLayout l9Layout = new javax.swing.GroupLayout(l9);
        l9.setLayout(l9Layout);
        l9Layout.setHorizontalGroup(
            l9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        l9Layout.setVerticalGroup(
            l9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l9);
        l9.setBounds(460, 710, 380, 10);

        t4e.setForeground(new java.awt.Color(204, 255, 255));
        t4e.setText("Number is requred");
        getContentPane().add(t4e);
        t4e.setBounds(720, 510, 130, 15);

        t2e2.setForeground(new java.awt.Color(204, 255, 255));
        t2e2.setText("Vechile number is 6 numbers");
        getContentPane().add(t2e2);
        t2e2.setBounds(670, 370, 180, 15);

        t3e1.setForeground(new java.awt.Color(204, 255, 255));
        t3e1.setText("Color is requred");
        getContentPane().add(t3e1);
        t3e1.setBounds(740, 430, 110, 15);

        t1e2.setForeground(new java.awt.Color(204, 255, 255));
        t1e2.setText("Ssn is 9 numbers");
        getContentPane().add(t1e2);
        t1e2.setBounds(740, 270, 110, 15);

        t5e.setForeground(new java.awt.Color(204, 255, 255));
        t5e.setText("Capacity is requred");
        getContentPane().add(t5e);
        t5e.setBounds(720, 590, 130, 15);

        t6e.setForeground(new java.awt.Color(204, 255, 255));
        t6e.setText("Model is requred");
        getContentPane().add(t6e);
        t6e.setBounds(740, 670, 110, 15);

        t1e1.setForeground(new java.awt.Color(204, 255, 255));
        t1e1.setText("Ssn is requred");
        getContentPane().add(t1e1);
        t1e1.setBounds(750, 270, 100, 15);

        t2e1.setForeground(new java.awt.Color(204, 255, 255));
        t2e1.setText("Vechile number is requred");
        getContentPane().add(t2e1);
        t2e1.setBounds(690, 350, 160, 20);

        t2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(204, 204, 204));
        t2.setText("Vechile number");
        t2.setBorder(null);
        t2.setOpaque(false);
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t2MouseExited(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(530, 320, 310, 70);

        t1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(204, 204, 204));
        t1.setText("Ssn");
        t1.setBorder(null);
        t1.setOpaque(false);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t1MouseExited(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(530, 240, 310, 70);

        t3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t3.setForeground(new java.awt.Color(204, 204, 204));
        t3.setText("Vechile color");
        t3.setBorder(null);
        t3.setOpaque(false);
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t3MouseExited(evt);
            }
        });
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(530, 400, 310, 70);

        t4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t4.setForeground(new java.awt.Color(204, 204, 204));
        t4.setText("Passengers number");
        t4.setToolTipText("");
        t4.setBorder(null);
        t4.setOpaque(false);
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t4MouseExited(evt);
            }
        });
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t4KeyPressed(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(530, 480, 310, 70);

        t5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t5.setForeground(new java.awt.Color(204, 204, 204));
        t5.setText("Engine capacity");
        t5.setBorder(null);
        t5.setOpaque(false);
        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t5MouseExited(evt);
            }
        });
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t5KeyPressed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(530, 560, 312, 70);

        t6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t6.setForeground(new java.awt.Color(204, 204, 204));
        t6.setText("Vechile model");
        t6.setBorder(null);
        t6.setOpaque(false);
        t6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t6MouseExited(evt);
            }
        });
        t6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t6KeyPressed(evt);
            }
        });
        getContentPane().add(t6);
        t6.setBounds(530, 640, 312, 70);

        s7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout s7Layout = new javax.swing.GroupLayout(s7);
        s7.setLayout(s7Layout);
        s7Layout.setHorizontalGroup(
            s7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        s7Layout.setVerticalGroup(
            s7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(s7);
        s7.setBounds(460, 720, 70, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 740, 60, 20);

        javax.swing.GroupLayout l12Layout = new javax.swing.GroupLayout(l12);
        l12.setLayout(l12Layout);
        l12Layout.setHorizontalGroup(
            l12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        l12Layout.setVerticalGroup(
            l12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(l12);
        l12.setBounds(450, 790, 140, 100);

        javax.swing.GroupLayout l10Layout = new javax.swing.GroupLayout(l10);
        l10.setLayout(l10Layout);
        l10Layout.setHorizontalGroup(
            l10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        l10Layout.setVerticalGroup(
            l10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(l10);
        l10.setBounds(710, 790, 140, 100);

        pp.setBackground(new java.awt.Color(204, 204, 204));
        pp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ppMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Save");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout ppLayout = new javax.swing.GroupLayout(pp);
        pp.setLayout(ppLayout);
        ppLayout.setHorizontalGroup(
            ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );
        ppLayout.setVerticalGroup(
            ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pp);
        pp.setBounds(600, 810, 95, 53);

        blue.setLayout(null);

        pi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insurance/2.png"))); // NOI18N
        pi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                piMouseEntered(evt);
            }
        });
        blue.add(pi);
        pi.setBounds(0, 0, 60, 55);

        getContentPane().add(blue);
        blue.setBounds(1140, 0, 60, 50);

        javax.swing.GroupLayout l11Layout = new javax.swing.GroupLayout(l11);
        l11.setLayout(l11Layout);
        l11Layout.setHorizontalGroup(
            l11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        l11Layout.setVerticalGroup(
            l11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(l11);
        l11.setBounds(590, 870, 120, 20);

        javax.swing.GroupLayout l13Layout = new javax.swing.GroupLayout(l13);
        l13.setLayout(l13Layout);
        l13Layout.setHorizontalGroup(
            l13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        l13Layout.setVerticalGroup(
            l13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(l13);
        l13.setBounds(590, 790, 120, 10);

        pp4.setBackground(new java.awt.Color(4, 73, 150));

        javax.swing.GroupLayout pp4Layout = new javax.swing.GroupLayout(pp4);
        pp4.setLayout(pp4Layout);
        pp4Layout.setHorizontalGroup(
            pp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pp4Layout.setVerticalGroup(
            pp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(pp4);
        pp4.setBounds(700, 800, 10, 70);

        pp2.setBackground(new java.awt.Color(4, 73, 150));

        javax.swing.GroupLayout pp2Layout = new javax.swing.GroupLayout(pp2);
        pp2.setLayout(pp2Layout);
        pp2Layout.setHorizontalGroup(
            pp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pp2Layout.setVerticalGroup(
            pp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(pp2);
        pp2.setBounds(600, 860, 100, 10);

        pp1.setBackground(new java.awt.Color(4, 73, 150));

        javax.swing.GroupLayout pp1Layout = new javax.swing.GroupLayout(pp1);
        pp1.setLayout(pp1Layout);
        pp1Layout.setHorizontalGroup(
            pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pp1Layout.setVerticalGroup(
            pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(pp1);
        pp1.setBounds(600, 800, 100, 10);

        pp3.setBackground(new java.awt.Color(4, 73, 150));

        javax.swing.GroupLayout pp3Layout = new javax.swing.GroupLayout(pp3);
        pp3.setLayout(pp3Layout);
        pp3Layout.setHorizontalGroup(
            pp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pp3Layout.setVerticalGroup(
            pp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(pp3);
        pp3.setBounds(590, 800, 10, 70);

        redp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redpMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                redpMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insurance/3.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout redpLayout = new javax.swing.GroupLayout(redp);
        redp.setLayout(redpLayout);
        redpLayout.setHorizontalGroup(
            redpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redpLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        redpLayout.setVerticalGroup(
            redpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redpLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(redp);
        redp.setBounds(1140, 0, 130, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insurance/all.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1300, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void pupllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pupllMouseClicked
ispublic=true;red=false;isprivate=false;
        this.puplight.setBackground(Color.WHITE);
       this.priveline.setBackground(new Color(5,89,165));
       this.pupline.setBackground(new Color(5,92,169));
        this.privelight.setBackground(new Color(5,92,169));
    }//GEN-LAST:event_pupllMouseClicked

    private void pupllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pupllMouseEntered
if(!red){        this.pupline.setBackground(new Color(1,58,137));
     
        this.priveline.setBackground(new Color(5,92,169));}
       

    }//GEN-LAST:event_pupllMouseEntered

    private void publMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publMouseClicked
ispublic=true;red=false;isprivate=false;
        this.puplight.setBackground(Color.WHITE);
        this.priveline.setBackground(new Color(5,89,165));
       this.pupline.setBackground(new Color(5,92,169));
        this.privelight.setBackground(new Color(5,92,169));
    }//GEN-LAST:event_publMouseClicked

    private void publMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publMouseEntered
if(!red){        this.pupline.setBackground(new Color(1,58,137));
 
        this.priveline.setBackground(new Color(5,92,169));}
       
    }//GEN-LAST:event_publMouseEntered

    private void publMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publMouseExited
if(!red)        this.pupline.setBackground(new Color(5,92,169));
        
    }//GEN-LAST:event_publMouseExited

    private void privMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_privMouseClicked
isprivate=true;red=false;ispublic=false;
        this.privelight.setBackground(Color.WHITE);
       this.priveline.setBackground(new Color(5,89,165));
       this.pupline.setBackground(new Color(5,92,169));
        this.puplight.setBackground(new Color(5,92,169));
    }//GEN-LAST:event_privMouseClicked

    private void privMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_privMouseEntered
 
        if(!red){
        this.priveline.setBackground(new Color(1,58,137));
 
        this.pupline.setBackground(new Color(5,92,169));}
    
    }//GEN-LAST:event_privMouseEntered

    private void piveeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piveeMouseClicked
isprivate=true;red=false;ispublic=false;
        this.privelight.setBackground(Color.WHITE);
        this.priveline.setBackground(new Color(5,89,165));
       this.pupline.setBackground(new Color(5,92,169));
        this.puplight.setBackground(new Color(5,92,169));
    }//GEN-LAST:event_piveeMouseClicked

    private void piveeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piveeMouseEntered

        if(!red){
        this.priveline.setBackground(new Color(1,58,137));
 
        this.pupline.setBackground(new Color(5,92,169));
       
}
    }//GEN-LAST:event_piveeMouseEntered

    private void piveeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piveeMouseExited
if(!red)         this.priveline.setBackground(new Color(7,89,165));
       
  
    }//GEN-LAST:event_piveeMouseExited

    private void jLabel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyPressed
         
    }//GEN-LAST:event_jLabel3KeyPressed

    private void ppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppMouseClicked
     boolean b1,b2,b3,b4,b5,b6,b7;
      m1=m2=m3=m4=m5=m6=false;
        if(this.t1.getText().equals("")){this.t1e1.setVisible(true);b1=false;this.t1e2.setVisible(false);}
        else if(this.t1.getText().equals("Ssn")){this.t1e1.setVisible(true);this .t1e2.setVisible(false);this.t1.setText("");b1=false;}
        else {
        int number=0;int length=0;
        for(int i=0;i<this.t1.getText().length();i++){length++;
        if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
        if(number==this.t1.getText().length()&&length==9){
        this.t1e2.setVisible(false);b1=true;}
        else{this.t1e1.setVisible(false);b1=false;}}
      
        if(this.t2.getText().equals("")){this.t2e1.setVisible(true);b2=false;this.t2e2.setVisible(false);}
        else if(this.t2.getText().equals("Vechile number")){this.t2e1.setVisible(true);this.t2.setText("");b2=false;this.t2e2.setVisible(false);}
   
        else {
        int number=0;int length=0;
        for(int i=0;i<this.t2.getText().length();i++){length++;
        if (Character.isDigit(this.t2.getText().charAt(i)))number++;}
        if(number==this.t2.getText().length()&&length==6){
        this.t2e2.setVisible(false);b2=true;}else{this.t2e2.setVisible(true);b2=false;}}
      
        if(this.t3.getText().equals("")){this.t3e1.setVisible(true);b3=false;}
        else if(this.t3.getText().equals("Vechile color")){this.t3e1.setVisible(true);this.t3.setText("");b3=false;}
        else {this.t3e1.setVisible(false);b3=true;}
        if(this.t4.getText().equals("")){this.t4e.setVisible(true);b4=false;}
        else if(this.t4.getText().equals("Passengers number")){this.t4e.setVisible(true);this.t4.setText("");b4=false;}
        else {
             int number=0;
        for(int i=0;i<this.t4.getText().length();i++)
        if (Character.isDigit(this.t4.getText().charAt(i)))number++;
        if(number==this.t4.getText().length()){
            this.t4e.setVisible(false);;b4=true;}else { this.t4e.setVisible(true);b4=false;}}
        if(this.t5.getText().equals("")){this.t5e.setVisible(true);b5=false;}
        else if(this.t5.getText().equals("Engine capacity")){this.t5e.setVisible(true);this.t5.setText("");b5=false;}
       
        else {
             int number=0;
        for(int i=0;i<this.t5.getText().length();i++)
        if (Character.isDigit(this.t5.getText().charAt(i)))number++;
        if(number==this.t5.getText().length()){
            this.t5e.setVisible(false);b5=true;}else { this.t5e.setVisible(true);b5=false;}}
      
        if(this.t6.getText().equals("")){this.t6e.setVisible(true);b6=false;}
        else if(this.t6.getText().equals("Vechile model")){this.t6e.setVisible(true);this.t6.setText("");b6=false;}
        else {this.t6e.setVisible(false);b6=true;}
      
        if(isprivate==false&&ispublic==false){red=true;b7=false;this.priveline.setBackground(Color.RED);this.pupline.setBackground(Color.RED);}
        else {b7=true;red=false;}
     /////////////////////////////////////////////////////////////////////////////////////////////
     ////////////////////////////////////////////////////////////////////////////////////////////
     ////////////////////////////////////////////////////////////////////////////////////////////
     if(b1&&b2&&b3&&b4&&b5&&b6&&b7){
         
         ////////////////////////////////////////////
         
         //raed
         ///////////////////////////////////////////////////
       Boolean f=true;
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Insurance_1PU");
            EntityManager em=emf.createEntityManager();
            InsuranceAccount IA= new InsuranceAccount();
            String s1=t1.getText();
            String s2=t2.getText();
            String s3=t3.getText();
            String s4=t4.getText();
            String s5=t5.getText();
            String s6=t6.getText();
            String s7="";
            if(isprivate==true)
                s7="Private";
            else s7="Public";
            InsuranceAccountPK IAPK= new InsuranceAccountPK(Long.parseLong(s1),Integer.parseInt(s2));
            IA.setInsuranceAccountPK(IAPK);
            IA.setVechileColor(s3);
            IA.setPassengerNum(Short.parseShort(s4));
            IA.setEngineCapacity(Integer.parseInt(s5));
            IA.setVechileModel(Short.parseShort(s6));
            IA.setVechileType(s7);
            em.getTransaction().begin();
            em.persist(IA);
            em.getTransaction().commit();
            em.close();
          
            
         
          if(f==true){
        JOptionPane.showMessageDialog(null, "Done");
       this.t1.setText("Ssn");
       this.t2.setText("Vechile number");
       this.t3.setText("Vechile color");
       this.t4.setText("Passengers number");
       this.t5.setText("Engine capacity");
       this.t6.setText("Vechile model");
       this.privelight.setBackground(new Color(7,99,168));
        this.puplight.setBackground(new Color(7,99,168));
          this.t1e2.setVisible(false);
         this.t2e2.setVisible(false);
         this.t3e1.setVisible(false);
         this.t4e.setVisible(false);
         this.t5e.setVisible(false);
         this.t6e.setVisible(false);
         this.t1e1.setVisible(false);
         this.t2e1.setVisible(false);           
         redp.setVisible(false);
         this.t3e2.setVisible(false); 
         m1=m2=m3=m4=m5=m6=m7=isprivate=ispublic=false;
         click=true;
       this.t1.requestFocus(rootPaneCheckingEnabled);}
       
      
       
       
       
       
       
       
       ///////////////////////////////////////////////////////
       
       
       
       
     }

    }//GEN-LAST:event_ppMouseClicked

    private void ppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppMouseEntered
        this.pp1.setOpaque(false);
        this.pp1.repaint();
        this.pp2.setOpaque(false);
        this.pp2.repaint();
        this.pp3.setOpaque(false);
        this.pp3.repaint();
        this.pp4.setOpaque(false);
        this.pp4.repaint();
    }//GEN-LAST:event_ppMouseEntered

    private void ppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppMouseExited
        this.pp1.setOpaque(true);
        this.pp1.repaint();
        this.pp2.setOpaque(true);
        this.pp2.repaint();
        this.pp3.setOpaque(true);
        this.pp3.repaint();
        this.pp4.setOpaque(true);
        this.pp4.repaint();
    }//GEN-LAST:event_ppMouseExited

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
         if(evt.getKeyCode()!=KeyEvent.VK_ENTER&&evt.getKeyCode()!=KeyEvent.VK_UP&&
                   evt.getKeyCode()!=KeyEvent.VK_DOWN){
            
               m1=true;
              
               this.t1e1.setVisible(false);
                int number=0;int length=0;
        
           if(this.t1.getText().equals("Ssn")) 
        this.t1.setText("");
            
             if(evt.getKeyCode()==8){   
             for(int i=0;i<this.t1.getText().length();i++){length++;
        if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
         if((number==this.t1.getText().length()&&length==10)){
                  this.t1e2.setVisible(false);}}
         
              for(int i=0;i<this.t1.getText().length();i++){length++;
        if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
         if(number==this.t1.getText().length()&&length==8){
                  this.t1e2.setVisible(false);}
       

       

       }
           else if(evt.getKeyCode()==KeyEvent.VK_UP)  {
                  this.t6.requestFocus(rootPaneCheckingEnabled);
               if(this.t1.getText().equals("")&&m1){
               this.t1.setText("Ssn");this.t1e1.setVisible(false);this.t1e2.setVisible(false);}
               else if(this.t1.getText().equals("Ssn")&&m1)
               {this.t1e2.setVisible(false);this.t1e1.setVisible(false);}
               else{ 
                   if(m1){
                int number=0;int length=0;
        
        
            
              for(int i=0;i<this.t1.getText().length();i++){length++;
        if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
        if(number==this.t1.getText().length()&&length==9){
           
             this.t1e2.setVisible(false);}else{
          this.t1e2.setVisible(true);} 
     
 
           
                   }           }}
              else if(evt.getKeyCode()==KeyEvent.VK_DOWN)  {
                         this.t2.requestFocus(rootPaneCheckingEnabled);
                  if(this.t1.getText().equals("")&&m1){
               this.t1.setText("Ssn");this.t1e1.setVisible(false);this.t1e2.setVisible(false);}
                  else if(this.t1.getText().equals("Ssn")&&m1)
               {this.t1e2.setVisible(false);this.t1e1.setVisible(false);}
               else{ 
                      if(m1){
                int number=0;int length=0;
        
        
            
              for(int i=0;i<this.t1.getText().length();i++){length++;
        if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
        if(number==this.t1.getText().length()&&length==9){
           
             this.t1e2.setVisible(false);this.t1e1.setVisible(false); }else{
            this.t1e2.setVisible(true);} 
 
 
           
           }} }
       else{
                    this.t2.requestFocus(rootPaneCheckingEnabled);
                    if(this.t1.getText().equals("")&&m1){this.t1.setText("Ssn");this.t1e1.setVisible(false);this.t1e2.setVisible(false);}
                    else if(this.t1.getText().equals("Ssn")&&m1){this.t1e1.setVisible(false);this.t1e2.setVisible(false);}
                    else{    
                        if(m1){
                       
                int number=0;int length=0;
              for(int i=0;i<this.t1.getText().length();i++){length++;
        if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
        if(number==this.t1.getText().length()&&length==9){
                  this.t1e2.setVisible(false);}
        else{t1e2.setVisible(true);}
        this.t2.requestFocus(rootPaneCheckingEnabled);
        if(this.t1.getText().equals("")){this.t1.setText("Ssn");this.t1e2.setVisible(false);this.t1e1.setVisible(false);}
                    }}
       }
    }//GEN-LAST:event_t1KeyPressed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
      if(evt.getKeyCode()!=KeyEvent.VK_ENTER&&evt.getKeyCode()!=KeyEvent.VK_UP&&
                   evt.getKeyCode()!=KeyEvent.VK_DOWN){
             if(this.t2.getText().equals("Vechile number"))
            this.t2.setText("");
          
          m2=true;this.t2e1.setVisible(false);
              int number=0;int length=0;
               if(evt.getKeyCode()==8){   
             for(int i=0;i<this.t2.getText().length();i++){length++;
        if (Character.isDigit(this.t2.getText().charAt(i)))number++;}
         if((number==this.t2.getText().length()&&length==7)){
                  this.t2e2.setVisible(false);}}
         
              for(int i=0;i<this.t2.getText().length();i++){length++;
        if (Character.isDigit(this.t2.getText().charAt(i)))number++;}
         if(number==this.t2.getText().length()&&length==5){
                  this.t2e2.setVisible(false);}
              
          
        }
           else if(evt.getKeyCode()==KeyEvent.VK_UP){
                  this.t1.requestFocus(rootPaneCheckingEnabled);
                if(this.t2.getText().equals("")&&m2)
                {this.t2.setText("Vechile number");this.t2e1.setVisible(false);this.t2e2.setVisible(false);}
                else if(this.t2.getText().equals("Vechile number")&&m2)this.t2e2.setVisible(false);
             else{
                    if(m2){
                 int number=0;int length=0;
                 for(int i=0;i<this.t2.getText().length();i++){length++;
                     if(Character.isDigit(this.t2.getText().charAt(i)))number++;}
                 if(number==this.t2.getText().length()&&length==6){this.t2e2.setVisible(false);}else this.t2e2.setVisible(true);
             }}}
                      else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
                  this.t3.requestFocus(rootPaneCheckingEnabled);
                if(this.t2.getText().equals("")&&m2)
                {this.t2.setText("Vechile number");this.t2e1.setVisible(false);this.t2e2.setVisible(false);}
                else if(this.t2.getText().equals("Vechile number")&&m2)this.t2e2.setVisible(false);
             else{
                    if(m2){
                    
                 int number=0;int length=0;
                 for(int i=0;i<this.t2.getText().length();i++){length++;
                     if(Character.isDigit(this.t2.getText().charAt(i)))number++;}
                 if(number==this.t2.getText().length()&&length==6){this.t2e2.setVisible(false);}else this.t2e2.setVisible(true);
             }}}
        else{
             this.t3.requestFocus(rootPaneCheckingEnabled);
            if(this.t2.getText().equals("")&&m1)
            {this.t2.setText("Vechile number");this.t2e1.setVisible(false);this.t2e2.setVisible(false);}
            else if(this.t2.getText().equals("Vechile number")&&m2){this.t2e1.setVisible(false);this.t2e2.setVisible(false);}
            else{
                if(m2){
                  int number=0;int length=0;
                 for(int i=0;i<this.t2.getText().length();i++){length++;
                     if(Character.isDigit(this.t2.getText().charAt(i)))number++;}
                 if(number==this.t2.getText().length()&&length==6){this.t2e2.setVisible(false);}else this.t2e2.setVisible(true);
            }}
        }
    }//GEN-LAST:event_t2KeyPressed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
           if(evt.getKeyCode()!=KeyEvent.VK_ENTER&&evt.getKeyCode()!=KeyEvent.VK_UP&&
                   evt.getKeyCode()!=KeyEvent.VK_DOWN){
            this.t3e1.setVisible(false);m3=true;
            if(this.t3.getText().equals("Vechile color"))
            this.t3.setText("");
        }
             else if(evt.getKeyCode()==KeyEvent.VK_UP){
                  this.t2.requestFocus(rootPaneCheckingEnabled);
                if(this.t3.getText().equals("")&&m3)
                {this.t3.setText("Vechile color");this.t1e1.setVisible(false);this.t3e2.setVisible(false);}
                else if(this.t3.getText().equals("Vechile color")&&m3)this.t3e2.setVisible(false);
             else{
                    if(m3){
                 int number=0;
                 for(int i=0;i<this.t3.getText().length();i++)
                     if(Character.isAlphabetic(this.t3.getText().charAt(i)))number++;
                 if(number==this.t3.getText().length()){this.t3e2.setVisible(false);}else this.t3e2.setVisible(true);
             }}}
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
             this.t4.requestFocus(rootPaneCheckingEnabled);
                if(this.t3.getText().equals("")&&m3)
                {this.t3.setText("Vechile color");this.t3e1.setVisible(false);this.t3e2.setVisible(false);}
                else if(this.t3.getText().equals("Vechile color")&&m3)this.t3e2.setVisible(false);
             else{
                    if(m3){
                 int number=0;
                 for(int i=0;i<this.t3.getText().length();i++)
                     if(Character.isAlphabetic(this.t3.getText().charAt(i)))number++;
                 if(number==this.t3.getText().length()){this.t3e2.setVisible(false);}else this.t3e2.setVisible(true);}}}
        else{
           this.t4.requestFocus(rootPaneCheckingEnabled);
           if(this.t3.getText().equals("Vechile color")&&m3){ this.t3e1.setVisible(false);this.t3e2.setVisible(false);}
        else if(this.t3.getText().equals("")&&m3){this.t3.setText("Vechile color");
            this.t3e1.setVisible(false);this.t3e2.setVisible(false);}
       else{
            if(m3){
                 int number=0;
                 for(int i=0;i<this.t3.getText().length();i++)
                     if(Character.isAlphabetic(this.t3.getText().charAt(i)))number++;
                 if(number==this.t3.getText().length()){this.t3e2.setVisible(false);}else this.t3e2.setVisible(true);
             }}}
    }//GEN-LAST:event_t3KeyPressed

    private void t4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyPressed
      if(evt.getKeyCode()!=KeyEvent.VK_ENTER&&evt.getKeyCode()!=KeyEvent.VK_UP&&
                   evt.getKeyCode()!=KeyEvent.VK_DOWN){
             m4=true;
            if(this.t4.getText().equals("Passengers number"))
            this.t4.setText("");
        }
            else if(evt.getKeyCode()==KeyEvent.VK_UP){
                  this.t3.requestFocus(rootPaneCheckingEnabled);
                if(this.t4.getText().equals("")&&m4)
                {this.t4.setText("Passengers number");this.t4e.setVisible(false);this.t4e.setVisible(false);}
                else if(this.t4.getText().equals("Passengers number")&&m4)this.t4e.setVisible(false);
             else{
                    if(m4){
                 int number=0;
                 for(int i=0;i<this.t4.getText().length();i++)
                     if(Character.isDigit(this.t4.getText().charAt(i)))number++;
                 if(number==this.t4.getText().length()){this.t4e.setVisible(false);}else this.t4e.setVisible(true);
             }}}
             else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
             this.t6.requestFocus(rootPaneCheckingEnabled);
                if(this.t4.getText().equals("")&&m4)
                {this.t4.setText("Passengers number");this.t4e.setVisible(false);this.t4e.setVisible(false);}
                else if(this.t4.getText().equals("Passengers number")&&m4)this.t4e.setVisible(false);
              else{
                    if(m4){
                  int number=0;
                 for(int i=0;i<this.t4.getText().length();i++)
                     if(Character.isDigit(this.t4.getText().charAt(i)))number++;
                 if(number==this.t4.getText().length()){this.t4e.setVisible(false);}else this.t4e.setVisible(true);}}}
          else{
                  this.t5.requestFocus(rootPaneCheckingEnabled);
                  if(this.t4.getText().equals("")&&m4){this.t4.setText("Passengers number");this.t4e.setVisible(false);this.t4e.setVisible(false);}
                  else if(this.t4.getText().equals("Passengers number")&&m4){this.t4e.setVisible(false);this.t4e.setVisible(false);}
                  else{
                      if(m4){
                  int number=0;
                 for(int i=0;i<this.t4.getText().length();i++)
                     if(Character.isDigit(this.t4.getText().charAt(i)))number++;
                 if(number==this.t4.getText().length()){this.t4e.setVisible(false);}else this.t4e.setVisible(true);
             }}
             
             
             }
    }//GEN-LAST:event_t4KeyPressed

    private void t5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyPressed
        if(evt.getKeyCode()!=KeyEvent.VK_ENTER&&evt.getKeyCode()!=KeyEvent.VK_UP&&
                   evt.getKeyCode()!=KeyEvent.VK_DOWN){
             m5=true;
            if(this.t5.getText().equals("Engine capacity"))
            this.t5.setText("");
        }
            else if(evt.getKeyCode()==KeyEvent.VK_UP){
                  this.t4.requestFocus(rootPaneCheckingEnabled);
                if(this.t5.getText().equals("")&&m5)
                {this.t5.setText("Engine capacity");this.t5e.setVisible(false);this.t5e.setVisible(false);}
                else if(this.t5.getText().equals("Engine capacity")&&m5)this.t5e.setVisible(false);
             else{
                    if(m5){
                 int number=0;
                 for(int i=0;i<this.t5.getText().length();i++)
                     if(Character.isDigit(this.t5.getText().charAt(i)))number++;
                 if(number==this.t5.getText().length()){this.t5e.setVisible(false);}else this.t5e.setVisible(true);
             }}}
             else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
             this.t6.requestFocus(rootPaneCheckingEnabled);
                if(this.t5.getText().equals("")&&m5)
                {this.t5.setText("Engine capacity");this.t5e.setVisible(false);this.t5e.setVisible(false);}
                else if(this.t5.getText().equals("Engine capacity")&&m5)this.t5e.setVisible(false);
              else{
                    if(m5){
                  int number=0;
                 for(int i=0;i<this.t5.getText().length();i++)
                     if(Character.isDigit(this.t5.getText().charAt(i)))number++;
                 if(number==this.t5.getText().length()){this.t5e.setVisible(false);}else this.t5e.setVisible(true);}}}
          else{
                  this.t6.requestFocus(rootPaneCheckingEnabled);
                  if(this.t5.getText().equals("")&&m5){this.t5.setText("Engine capacity");this.t5e.setVisible(false);this.t5e.setVisible(false);}
                  else if(this.t5.getText().equals("Engine capacity")&&m5){this.t5e.setVisible(false);this.t5e.setVisible(false);}
                  else{
                      if(m5){
                  int number=0;
                 for(int i=0;i<this.t5.getText().length();i++)
                     if(Character.isDigit(this.t5.getText().charAt(i)))number++;
                 if(number==this.t5.getText().length()){this.t5e.setVisible(false);}else this.t5e.setVisible(true);
             }}
             
             
             }
    }//GEN-LAST:event_t5KeyPressed

    private void t6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t6KeyPressed
             if(evt.getKeyCode()!=KeyEvent.VK_ENTER&&evt.getKeyCode()!=KeyEvent.VK_UP&&
                   evt.getKeyCode()!=KeyEvent.VK_DOWN){
                 m6=true;
                 this.t6e.setVisible(false);
          if(this.t6.getText().equals("Vechile model")) 
        this.t6.setText("");
       }
              else if(evt.getKeyCode()==KeyEvent.VK_UP)  {if(this.t6.getText().equals("")&&m6)this.t6.setText("Vechile model");
               this.t5.requestFocus(rootPaneCheckingEnabled);}
           else if(evt.getKeyCode()==KeyEvent.VK_DOWN)  {if(this.t6.getText().equals("")&&m6)this.t6.setText("Vechile model");
               this.t1.requestFocus(rootPaneCheckingEnabled);}
           else{
             
              m1=m2=m3=m4=m5=m6=false;
        boolean b1,b2,b3,b4,b5,b6,b7;
         if(this.t1.getText().equals("")){this.t1e1.setVisible(true);b1=false;}
        else if(this.t1.getText().equals("Ssn")){this.t1e1.setVisible(true);this.t1.setText("");b1=false;}
        else {
            int number=0;int length=0;
            for(int i=0;i<this.t1.getText().length();i++){
                length++;if(Character.isDigit(this.t1.getText().charAt(i)))number++;
            }
            if(number==this.t1.getText().length()&&length==9){this.t1e2.setVisible(false);b1=true;}
            else{this.t1e2.setVisible(true);b1=false;}
        }
      
            if(this.t2.getText().equals("")){this.t2e1.setVisible(true);b2=false;}
        else if(this.t2.getText().equals("Vechile number")){this.t2e1.setVisible(true);this.t2.setText("");b2=false;}
        else {
            int number=0;int length=0;
            for(int i=0;i<this.t2.getText().length();i++){
                length++;if(Character.isDigit(this.t2.getText().charAt(i)))number++;
            }
            if(number==this.t2.getText().length()&&length==6){this.t2e2.setVisible(false);b2=true;}
            else{this.t2e2.setVisible(true);b2=false;}
        }
            
        if(this.t3.getText().equals("")){this.t3e1.setVisible(true);b3=false;}
        else if(this.t3.getText().equals("Vechile color")){this.t3e1.setVisible(true);this.t3.setText("");b3=false;}
        else{ 
            int number=0;
            for(int i=0;i<this.t3.getText().length();i++)if(Character.isAlphabetic(this.t3.getText().charAt(i)))number++;
            if(number==this.t3.getText().length()){this.t3e2.setVisible(false);b3=true;}else{
            this.t3e2.setVisible(true);b3=false;}
            this.t3e1.setVisible(false);b3=true;}
        
     if(this.t4.getText().equals("")){this.t4e.setVisible(true);b4=false;}
        else if(this.t4.getText().equals("Passengers number")){this.t4e.setVisible(true);this.t4.setText("");b4=false;}
        else{ 
            int number=0;
            for(int i=0;i<this.t4.getText().length();i++)if(Character.isDigit(this.t4.getText().charAt(i)))number++;
            if(number==this.t4.getText().length()){this.t4e.setVisible(false);b4=true;}else{
            this.t4e.setVisible(true);b4=false;}
            }
        
       
      if(this.t5.getText().equals("")){this.t5e.setVisible(true);b5=false;}
        else if(this.t5.getText().equals("Engine capacity")){this.t5e.setVisible(true);this.t5.setText("");b5=false;}
        else{ 
            int number=0;
            for(int i=0;i<this.t5.getText().length();i++)if(Character.isDigit(this.t5.getText().charAt(i)))number++;
            if(number==this.t5.getText().length()){this.t5e.setVisible(false);b5=true;}else{
            this.t5e.setVisible(true);b5=false;}
            this.t5e.setVisible(false);b5=true;}
        
      
        if(this.t6.getText().equals("")){this.t6e.setVisible(true);b6=false;}
        else if(this.t6.getText().equals("Vechile model")){this.t6e.setVisible(true);this.t6.setText("");b6=false;}
        else {this.t6e.setVisible(false);b6=true;}
      
        if(isprivate==false&&ispublic==false){red=true;b7=false;this.priveline.setBackground(Color.RED);this.pupline.setBackground(Color.RED);}
        else {b7=true;red=false;}
 /////////////////////////////////////////////////////////////////////////////////////////////
     ////////////////////////////////////////////////////////////////////////////////////////////
     ////////////////////////////////////////////////////////////////////////////////////////////
     if(b1&&b2&&b3&&b4&&b5&&b6&&b7){
         ////////////////////////////////////////////
         
         //raed
         ///////////////////////////////////////////////////
       Boolean f=true;
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Insurance_1PU");
            EntityManager em=emf.createEntityManager();
            InsuranceAccount IA= new InsuranceAccount();
            String s1=t1.getText();
            String s2=t2.getText();
            String s3=t3.getText();
            String s4=t4.getText();
            String s5=t5.getText();
            String s6=t6.getText();
            String s7="";
            if(isprivate==true)
                s7="Private";
            else s7="Public";
            InsuranceAccountPK IAPK= new InsuranceAccountPK(Long.parseLong(s1),Integer.parseInt(s2));
            IA.setInsuranceAccountPK(IAPK);
            IA.setVechileColor(s3);
            IA.setPassengerNum(Short.parseShort(s4));
            IA.setEngineCapacity(Integer.parseInt(s5));
            IA.setVechileModel(Short.parseShort(s6));
            IA.setVechileType(s7);
            em.getTransaction().begin();
            em.persist(IA);
            em.getTransaction().commit();
            em.close();
          
            
         
          if(f==true){
        JOptionPane.showMessageDialog(null, "Done");
       this.t1.setText("Ssn");
       this.t2.setText("Vechile number");
       this.t3.setText("Vechile color");
       this.t4.setText("Passengers number");
       this.t5.setText("Engine capacity");
       this.t6.setText("Vechile model");
       this.privelight.setBackground(new Color(7,99,168));
        this.puplight.setBackground(new Color(7,99,168));
          this.t1e2.setVisible(false);
         this.t2e2.setVisible(false);
         this.t3e1.setVisible(false);
         this.t4e.setVisible(false);
         this.t5e.setVisible(false);
         this.t6e.setVisible(false);
         this.t1e1.setVisible(false);
         this.t2e1.setVisible(false);           
         redp.setVisible(false);
         this.t3e2.setVisible(false); 
         m1=m2=m3=m4=m5=m6=m7=isprivate=ispublic=false;
         click=true;
       this.t1.requestFocus(rootPaneCheckingEnabled);}
     }
           }
    }//GEN-LAST:event_t6KeyPressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
 m1=m2=m3=m4=m5=m6=false;
        boolean b1,b2,b3,b4,b5,b6,b7;
         if(this.t1.getText().equals("")){this.t1e1.setVisible(true);b1=false;}
        else if(this.t1.getText().equals("Ssn")){this.t1e1.setVisible(true);this.t1.setText("");b1=false;}
        else {
            int number=0;int length=0;
            for(int i=0;i<this.t1.getText().length();i++){
                length++;if(Character.isDigit(this.t1.getText().charAt(i)))number++;
            }
            if(number==this.t1.getText().length()&&length==9){this.t1e2.setVisible(false);b1=true;}
            else{this.t1e2.setVisible(true);b1=false;}
        }
      
            if(this.t2.getText().equals("")){this.t2e1.setVisible(true);b2=false;}
        else if(this.t2.getText().equals("Vechile number")){this.t2e1.setVisible(true);this.t2.setText("");b2=false;}
        else {
            int number=0;int length=0;
            for(int i=0;i<this.t2.getText().length();i++){
                length++;if(Character.isDigit(this.t2.getText().charAt(i)))number++;
            }
            if(number==this.t2.getText().length()&&length==6){this.t2e2.setVisible(false);b2=true;}
            else{this.t2e2.setVisible(true);b2=false;}
        }
            
        if(this.t3.getText().equals("")){this.t3e1.setVisible(true);b3=false;}
        else if(this.t3.getText().equals("Vechile color")){this.t3e1.setVisible(true);this.t3.setText("");b3=false;}
        else{ 
            int number=0;
            for(int i=0;i<this.t3.getText().length();i++)if(Character.isAlphabetic(this.t3.getText().charAt(i)))number++;
            if(number==this.t3.getText().length()){this.t3e2.setVisible(false);b3=true;}else{
            this.t3e2.setVisible(true);b3=false;}
            this.t3e1.setVisible(false);b3=true;}
        
     if(this.t4.getText().equals("")){this.t4e.setVisible(true);b4=false;}
        else if(this.t4.getText().equals("Passengers number")){this.t4e.setVisible(true);this.t4.setText("");b4=false;}
        else{ 
            int number=0;
            for(int i=0;i<this.t4.getText().length();i++)if(Character.isDigit(this.t4.getText().charAt(i)))number++;
            if(number==this.t4.getText().length()){this.t4e.setVisible(false);b4=true;}else{
            this.t4e.setVisible(true);b4=false;}
            }
        
       
      if(this.t5.getText().equals("")){this.t5e.setVisible(true);b5=false;}
        else if(this.t5.getText().equals("Engine capacity")){this.t5e.setVisible(true);this.t5.setText("");b5=false;}
        else{ 
            int number=0;
            for(int i=0;i<this.t5.getText().length();i++)if(Character.isDigit(this.t5.getText().charAt(i)))number++;
            if(number==this.t5.getText().length()){this.t5e.setVisible(false);b5=true;}else{
            this.t5e.setVisible(true);b5=false;}
            this.t5e.setVisible(false);b5=true;}
        
      
        if(this.t6.getText().equals("")){this.t6e.setVisible(true);b6=false;}
        else if(this.t6.getText().equals("Vechile model")){this.t6e.setVisible(true);this.t6.setText("");b6=false;}
        else {this.t6e.setVisible(false);b6=true;}
      
        if(isprivate==false&&ispublic==false){red=true;b7=false;this.priveline.setBackground(Color.RED);this.pupline.setBackground(Color.RED);}
        else {b7=true;red=false;}
      /////////////////////////////////////////////////////////////////////////////////////////////
     ////////////////////////////////////////////////////////////////////////////////////////////
     ////////////////////////////////////////////////////////////////////////////////////////////
     if(b1&&b2&&b3&&b4&&b5&&b6&&b7){
        ////////////////////////////////////////////
         
         //raed
         ///////////////////////////////////////////////////
        Boolean f=true;
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Insurance_1PU");
            EntityManager em=emf.createEntityManager();
            InsuranceAccount IA= new InsuranceAccount();
            String s1=t1.getText();
            String s2=t2.getText();
            String s3=t3.getText();
            String s4=t4.getText();
            String s5=t5.getText();
            String s6=t6.getText();
            String s7="";
            if(isprivate==true)
                s7="Private";
            else s7="Public";
            InsuranceAccountPK IAPK= new InsuranceAccountPK(Long.parseLong(s1),Integer.parseInt(s2));
            IA.setInsuranceAccountPK(IAPK);
            IA.setVechileColor(s3);
            IA.setPassengerNum(Short.parseShort(s4));
            IA.setEngineCapacity(Integer.parseInt(s5));
            IA.setVechileModel(Short.parseShort(s6));
            IA.setVechileType(s7);
            em.getTransaction().begin();
            em.persist(IA);
            em.getTransaction().commit();
            em.close();
          
            
         
          if(f==true){
        JOptionPane.showMessageDialog(null, "Done");
       this.t1.setText("Ssn");
       this.t2.setText("Vechile number");
       this.t3.setText("Vechile color");
       this.t4.setText("Passengers number");
       this.t5.setText("Engine capacity");
       this.t6.setText("Vechile model");
       this.privelight.setBackground(new Color(7,99,168));
        this.puplight.setBackground(new Color(7,99,168));
          this.t1e2.setVisible(false);
         this.t2e2.setVisible(false);
         this.t3e1.setVisible(false);
         this.t4e.setVisible(false);
         this.t5e.setVisible(false);
         this.t6e.setVisible(false);
         this.t1e1.setVisible(false);
         this.t2e1.setVisible(false);           
         redp.setVisible(false);
         this.t3e2.setVisible(false); 
         m1=m2=m3=m4=m5=m6=m7=isprivate=ispublic=false;
         click=true;
       this.t1.requestFocus(rootPaneCheckingEnabled);}
      
     }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseExited
   if(this.t1.getText().equals("")&&m1){
               this.t1.setText("Ssn");this.t1e1.setVisible(false);this.t1e2.setVisible(false);}
                  else if(this.t1.getText().equals("Ssn")&&m1)
               {this.t1e2.setVisible(false);this.t1e1.setVisible(false);}
               else{ 
                      if(m1){
                int number=0;int length=0;
        
        
            
              for(int i=0;i<this.t1.getText().length();i++){length++;
        if (Character.isDigit(this.t1.getText().charAt(i)))number++;}
        if(number==this.t1.getText().length()&&length==9){
           
             this.t1e2.setVisible(false);this.t1e1.setVisible(false); }else{
            this.t1e2.setVisible(true);} 
 
 
           
           }}     }//GEN-LAST:event_t1MouseExited

    private void t2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseExited
if(this.t2.getText().equals("")&&m2)
                {this.t2.setText("Vechile number");this.t2e1.setVisible(false);this.t2e2.setVisible(false);}
                else if(this.t2.getText().equals("Vechile number")&&m2)this.t2e2.setVisible(false);
             else{
                    if(m2){
                 int number=0;int length=0;
                 for(int i=0;i<this.t2.getText().length();i++){length++;
                     if(Character.isDigit(this.t2.getText().charAt(i)))number++;}
                 if(number==this.t2.getText().length()&&length==6){this.t2e2.setVisible(false);}else this.t2e2.setVisible(true);
             }}        
    }//GEN-LAST:event_t2MouseExited

    private void t3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MouseExited
 if(this.t3.getText().equals("")&&m3)
                {this.t3.setText("Vechile color");this.t1e1.setVisible(false);this.t3e2.setVisible(false);}
                else if(this.t3.getText().equals("Vechile color")&&m3)this.t3e2.setVisible(false);
             else{
                    if(m3){
                 int number=0;
                 for(int i=0;i<this.t3.getText().length();i++)
                     if(Character.isAlphabetic(this.t3.getText().charAt(i)))number++;
                 if(number==this.t3.getText().length()){this.t3e2.setVisible(false);}else this.t3e2.setVisible(true);
             }}    }//GEN-LAST:event_t3MouseExited

    private void t4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t4MouseExited
   if(this.t4.getText().equals("")&&m4)
                {this.t4.setText("Passengers number");this.t4e.setVisible(false);this.t4e.setVisible(false);}
                else if(this.t4.getText().equals("Passengers number")&&m4)this.t4e.setVisible(false);
             else{
                    if(m4){
                 int number=0;
                 for(int i=0;i<this.t4.getText().length();i++)
                     if(Character.isDigit(this.t4.getText().charAt(i)))number++;
                 if(number==this.t4.getText().length()){this.t4e.setVisible(false);}else this.t4e.setVisible(true);
             }}    }//GEN-LAST:event_t4MouseExited

    private void t5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MouseExited
 if(this.t5.getText().equals("")&&m5)
                {this.t5.setText("Engine capacity");this.t5e.setVisible(false);this.t5e.setVisible(false);}
                else if(this.t5.getText().equals("Engine capacity")&&m5)this.t5e.setVisible(false);
             else{
                    if(m5){
                 int number=0;
                 for(int i=0;i<this.t5.getText().length();i++)
                     if(Character.isDigit(this.t5.getText().charAt(i)))number++;
                 if(number==this.t5.getText().length()){this.t5e.setVisible(false);}else this.t5e.setVisible(true);
             }}    }//GEN-LAST:event_t5MouseExited

    private void t6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t6MouseExited
  if(this.t6.getText().equals("")&&m6){this.t6e.setVisible(true);}
        else if(this.t6.getText().equals("Vechile model")&&m6){this.t6e.setVisible(true);this.t6.setText("");}
        else {if (m6)this.t6e.setVisible(false);}
          }//GEN-LAST:event_t6MouseExited

    private void piMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piMouseEntered
blue.setVisible(false);
redp.setVisible(true);
        
    
    }//GEN-LAST:event_piMouseEntered

    private void redpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redpMouseExited
redp.setVisible(false);
blue.setVisible(true);

    }//GEN-LAST:event_redpMouseExited

    private void redpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redpMouseClicked
        // TODO add your handling code hereset
        setVisible(false);
        
    }//GEN-LAST:event_redpMouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
       this.pp1.setOpaque(false);
        this.pp1.repaint();
        this.pp2.setOpaque(false);
        this.pp2.repaint();
        this.pp3.setOpaque(false);
        this.pp3.repaint();
        this.pp4.setOpaque(false);
        this.pp4.repaint();
    }//GEN-LAST:event_jLabel3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel blue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel l1;
    private javax.swing.JPanel l10;
    private javax.swing.JPanel l11;
    private javax.swing.JPanel l12;
    private javax.swing.JPanel l13;
    private javax.swing.JPanel l2;
    private javax.swing.JPanel l3;
    private javax.swing.JPanel l4;
    private javax.swing.JPanel l5;
    private javax.swing.JPanel l6;
    private javax.swing.JPanel l7;
    private javax.swing.JPanel l8;
    private javax.swing.JPanel l9;
    private javax.swing.JLabel pi;
    private javax.swing.JPanel pivee;
    private javax.swing.JPanel pp;
    private javax.swing.JPanel pp1;
    private javax.swing.JPanel pp2;
    private javax.swing.JPanel pp3;
    private javax.swing.JPanel pp4;
    private javax.swing.JLabel priv;
    private javax.swing.JPanel privelight;
    private javax.swing.JPanel priveline;
    private javax.swing.JPanel publ;
    private javax.swing.JPanel puplight;
    private javax.swing.JPanel pupline;
    private javax.swing.JLabel pupll;
    private javax.swing.JPanel redp;
    private javax.swing.JPanel s1;
    private javax.swing.JPanel s2;
    private javax.swing.JPanel s3;
    private javax.swing.JPanel s4;
    private javax.swing.JPanel s5;
    private javax.swing.JPanel s6;
    private javax.swing.JPanel s7;
    private javax.swing.JTextField t1;
    private javax.swing.JLabel t1e1;
    private javax.swing.JLabel t1e2;
    private javax.swing.JTextField t2;
    private javax.swing.JLabel t2e1;
    private javax.swing.JLabel t2e2;
    private javax.swing.JTextField t3;
    private javax.swing.JLabel t3e1;
    private javax.swing.JLabel t3e2;
    private javax.swing.JTextField t4;
    private javax.swing.JLabel t4e;
    private javax.swing.JTextField t5;
    private javax.swing.JLabel t5e;
    private javax.swing.JTextField t6;
    private javax.swing.JLabel t6e;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
